name: CI
on: [push, pull_request]

jobs:
  ci:
    name: Run CI
    strategy:
      fail-fast: false
      matrix:
        go: [1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test -race ./...
      - name: Run go vet
        run: go vet ./...
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          install-go: false
